; PlatformIO Project Configuration File
;
; PitchPls! discoball - ESP32 + TMC2209 stepper (NEMA17 17HE08-1004S)
;
; Docs: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^6.9.0
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    teemuatlut/TMCStepper@^0.7.3
    waspinator/AccelStepper@^1.64
