; PlatformIO Project Configuration File
;
; PitchPls! v3 - ESP32 DMX-in -> 4x WS2811 LED-out
;
; Docs: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^6.9.0
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    fastled/FastLED@^3.9.0
